console.log("Hello World");
let x=3;
console.log(x);
let y=x+5;
console.log(y);
let b=x*y;
console.log(b);
let c=x*y;
console.log(c);
let h=x/y;
console.log(h);
let g=x%y;
console.log(g);
let z=x++;
console.log(z);
let a=x--;
console.log(a);
let m=x-y;
console.log(m);